#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/runner/work/anvil/anvil/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/home/runner/work/anvil/anvil/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../@swc+core@1.2.182/node_modules/@swc/core/run_swcx.js" "$@"
else
  exec node  "$basedir/../../../../../@swc+core@1.2.182/node_modules/@swc/core/run_swcx.js" "$@"
fi
